### ISSUE TITLE
No installer for version 3.2.0

### ISSUE THREAD

**Issue by ScrapyHD** [akhilesh-balaji/Textylic#10]
Hi, is there going to be an installer released for version 3.2.0? I only see portable and source, Thanks!

**Comment by akhilesh-balaji** [comment]
Hi, sorry that I didn't add the installer. Please expect an installer to be added in the next few days.

**Comment by WouterVanGoey** [comment]
Hi, could you add the installer please? Or even better, get your app on scoop:

https://github.com/ScoopInstaller/BucketTemplate
https://github.com/ScoopInstaller/Scoop/wiki/Buckets
https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md

**Comment by akhilesh-balaji** [comment]
I have added the installer now—I will shortly look into Scoop. I have changed the installer platform to [Inno](https://jrsoftware.org/isdl.php); please inform me if you encounter any issues in the installation.
