### ISSUE TITLE
High DPI support?

### ISSUE THREAD

**Issue by Akash-116** [akhilesh-balaji/Textylic#6]
Hello,
When is the tentative date for next version release, with high DPI support?

Thanks

**Comment by akhilesh-balaji** [comment]
Hello,

I've had a lot going on recently, and thus did not work on this program as much. Hopefully, the next version will release within a few weeks, with High DPI support.

**Comment by akhilesh-balaji** [comment]
I've been working on a lot of projects recently, and didn't get much time to work on this one. Hopefully, the next version with HiDPI support will release in a few weeks.

**Comment by akhilesh-balaji** [comment]
#7 will resolve this

**Comment by akhilesh-balaji** [comment]
Closed by #7
